manipulator:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  link_1_controller:
    type: effort_controllers/JointPositionController
    joint: link_1_joint
    pid: {p: 1000.00, i: 200.00, d: 200.00}

  link_2_controller:
    type: effort_controllers/JointPositionController
    joint: link_2_joint
    pid: {p: 5000.00, i: 500.00, d: 500.00}

  link_3_controller:
    type: effort_controllers/JointPositionController
    joint: link_3_joint
    pid: {p: 1000.00, i: 750.00, d: 50.00}




  
